
/**
 * Exception class for invalid social security numbers.
 * @author Sebastian Ashcallay
 *
 */
public class SocSecException extends Exception {
	
	/* WARNING! The serializable class SocSecException does not declare a static 
	 * final serialVersionUID field of type long. The data member below dismisses
	 * this warning. The Exception class, for the purpose of our program, works
	 * regardless of this data member's existence.
	 * 
	 * NOTE: This serialVersionUID is generated by Eclipse
	*/
	
	private static final long serialVersionUID = -2484142775952443501L;

	/**
	 * Parameterized Constructor: SocSecException()
	 * @param error: Indicates the specific error that makes the SSN invalid.
	 */
	public SocSecException(String error) {
		super("Invalid social security number, " + error);
	}

}
